artifacts_root: artifacts

data_ingestion:
root_dir: artifacts/data_ingestion,
sourece_URL: https://github.com/ashokboppana1/Pandas/blob/main/WineQT.zip
local_data_file: artifacts/data_ingestion/data.zip
unzip_dir: artifacts/data_ingestion
